apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: jenkins-demo
  name: jenkins-demo
  namespace: demo
spec:
  containers:
  - image: poseidon1979/jenkins-demo
    name: jenkins-demo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
